# -*- coding: utf-8 -*-
"""proy_end_to_end_mineria_de_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFj2FilCWUtxYKnDauH1ALuAm-SonoGv
"""

# Commented out IPython magic to ensure Python compatibility.
#Conexion al dataset y carga de datos
#Para visualizar el dataset utilizado en este proyecto es posible dirigirse al siguiente link: https://www.kaggle.com/datasets/lakshmi25npathi/online-retail-dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

# %matplotlib inline
plt.style.use('seaborn-v0_8-whitegrid')
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

drive.mount('/content/drive')

ruta_2023_24 = '/content/drive/MyDrive/PROY INTELIGENCIA ANALITICA Y MINERIA DE DATOS/Sales 2023-24.csv'
ruta_2024_25 = '/content/drive/MyDrive/PROY INTELIGENCIA ANALITICA Y MINERIA DE DATOS/Sales 2024-25.csv'

def cargar_csv(ruta):
    try:
        return pd.read_csv(ruta, encoding='utf-8')
    except UnicodeDecodeError:
        return pd.read_csv(ruta, encoding='latin1')

df_year1 = cargar_csv(ruta_2023_24)
df_year2 = cargar_csv(ruta_2024_25)

print(f"/dataset cargado 2023-24: {df_year1.shape[0]:,} filas y {df_year1.shape[1]} columnas.")
print(f"/dataset cargado 2024-25: {df_year2.shape[0]:,} filas y {df_year2.shape[1]} columnas.")

df = pd.concat([df_year1, df_year2], axis=0, ignore_index=True)

del df_year1, df_year2
df.head()

print("/resumen de tipado de datos y columnas")
print(df.info())

print("\n /estadistica del dataset")
print(df.describe())

#limpieza de datos

n_inicial = len(df)
print(f"Total registros iniciales: {n_inicial:,}")

df.columns = df.columns.str.strip()
df.rename(columns={'Invoice': 'InvoiceNo', 'Customer ID': 'CustomerID', 'Price': 'UnitPrice'}, inplace=True)

duplicados = df.duplicated().sum()
print(f"Duplicados encontrados y eliminados: {duplicados:,}")
df.drop_duplicates(inplace=True)

#eliminacion de clientes nulos debido a que para el analisis es necesario entender quien es el cliente
nulos_clientes = df['CustomerID'].isnull().sum()
print(f"Registros sin CustomerID eliminados: {nulos_clientes:,}")
df.dropna(subset=['CustomerID'], inplace=True)

#para el analisis posterior no es necesario facturas canceladas
df['InvoiceNo'] = df['InvoiceNo'].astype(str)
cancelaciones = df['InvoiceNo'].str.upper().str.startswith('C').sum()
print(f"Facturas de cancelación (inician con 'C') eliminadas: {cancelaciones:,}")
df = df[~df['InvoiceNo'].str.upper().str.startswith('C')]

#depuracion de outliers
anomalias_qty_price = ((df['Quantity'] <= 0) | (df['UnitPrice'] <= 0)).sum()
print(f"Registros con Quantity o UnitPrice <= 0 eliminados: {anomalias_qty_price:,}")
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

df['CustomerID'] = df['CustomerID'].astype(int).astype(str) # Identificador en string
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], dayfirst=True) # Formato fecha

n_final = len(df)
eliminados = n_inicial - n_final

print("\n" + f"Registros limpios finales: {n_final:,}")
print(f"Total registros eliminados: {eliminados:,} ({(eliminados/n_inicial)*100:.2f}%)")

#creacion de variables (TotalAmount) y outliers

df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

print(df[['Quantity', 'UnitPrice', 'TotalAmount']].describe())

#boxplot
plt.figure(figsize=(14, 4))

plt.subplot(1, 3, 1)
sns.boxplot(y=df['Quantity'], color='skyblue')
plt.title('Distribución de Quantity')
plt.yscale('log') # Escala logarítmica para poder ver la distribución

plt.subplot(1, 3, 2)
sns.boxplot(y=df['UnitPrice'], color='lightgreen')
plt.title('Distribución de UnitPrice')
plt.yscale('log')

plt.subplot(1, 3, 3)
sns.boxplot(y=df['TotalAmount'], color='salmon')
plt.title('Distribución de TotalAmount')
plt.yscale('log')

plt.tight_layout()
plt.show()

#feature enginering (rfm)

fecha_corte = df['InvoiceDate'].max() + pd.Timedelta(days=1)
print(f"Fecha de analisis: {fecha_corte.strftime('%d/%m/%Y')}")

#agrupacion clientes
df_clientes = df.groupby('CustomerID').agg(
    Recency=('InvoiceDate', lambda date: (fecha_corte - date.max()).days),
    Frequency=('InvoiceNo', 'nunique'),
    Monetary=('TotalAmount', 'sum'),
    TotalQuantity=('Quantity', 'sum'),
    Country=('Country', 'first')
).reset_index()

# Feature Engineering variabels
df_clientes['AvgTicket'] = df_clientes['Monetary'] / df_clientes['Frequency']

df_clientes['Is_UK'] = (df_clientes['Country'] == 'United Kingdom').astype(int)

# churn
df_clientes['Churn'] = (df_clientes['Recency'] > 90).astype(int)

print(f"Distinct de clientes analizados: {df_clientes.shape[0]:,}")
print("\n Distribución de la variable objetivo (churn)")
print(df_clientes['Churn'].value_counts(normalize=True) * 100)

df_clientes.head()

#division del dataset (train, val, test)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#variables predictoras (X) y variable objetivo (y)
features = ['Frequency', 'Monetary', 'TotalQuantity', 'AvgTicket', 'Is_UK']
X = df_clientes[features]
y = df_clientes['Churn']

#partición: 70% Train, 30% Temporal (Val + Test)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y)

#partición: dividimos el 30% en dos partes iguales (15% Val y 15% Test)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

#escalamiento de variables con StandardScaler
scaler = StandardScaler()
# evitacion de contaminacion train
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

#dataset convertido
X_train_scaled = pd.DataFrame(X_train_scaled, columns=features)
X_val_scaled = pd.DataFrame(X_val_scaled, columns=features)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=features)

print(f"Conjunto de Entrenamiento (Train 70%): {X_train.shape[0]} registros")
print(f"Conjunto de Validación   (Val 15%):   {X_val.shape[0]} registros")
print(f"Conjunto de Prueba        (Test 15%):  {X_test.shape[0]} registros")

X_train_scaled.head()

#entrenamiento y comparacion de modelos de clasificacion
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

modelo_lr = LogisticRegression(random_state=42)
modelo_rf = RandomForestClassifier(n_estimators=100, max_depth=6, random_state=42)

#entramiento con el modelo training
modelo_lr.fit(X_train_scaled, y_train)
modelo_rf.fit(X_train, y_train) # Random Forest no requiere escalamiento estricto, usa X_train directamente

def calcular_metricas(modelo, X, y, escalado=False):
    y_pred = modelo.predict(X)
    y_prob = modelo.predict_proba(X)[:, 1]
    return {
        'Accuracy': accuracy_score(y, y_pred),
        'Precision': precision_score(y, y_pred),
        'Recall': recall_score(y, y_pred),
        'F1-Score': f1_score(y, y_pred),
        'AUC-ROC': roc_auc_score(y, y_prob)
    }

metricas_lr_val = calcular_metricas(modelo_lr, X_val_scaled, y_val)
metricas_rf_val = calcular_metricas(modelo_rf, X_val, y_val)

df_comparativa = pd.DataFrame([metricas_lr_val, metricas_rf_val], index=['Logistic Regression', 'Random Forest'])
print("comparativa tecnica")
print(df_comparativa.round(4))

#evaluacion en test y visualizaciones obligatorias del aca
from sklearn.metrics import confusion_matrix, roc_curve, auc, classification_report

#predicciones conjunto de prueba no visto (Test)
y_pred_test = modelo_rf.predict(X_test)
y_prob_test = modelo_rf.predict_proba(X_test)[:, 1]

print("reporte tecnico detallado en prueba (test)")
print(classification_report(y_test, y_pred_test, target_names=['Activo (0)', 'Churn (1)'], digits=4))

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Heatmap de la Matriz de Confusión
cm = confusion_matrix(y_test, y_pred_test)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0], cbar=False,
            xticklabels=['Pred. Activo (0)', 'Pred. Churn (1)'],
            yticklabels=['Real Activo (0)', 'Real Churn (1)'])
axes[0].set_title('Matriz de Confusion (Test)', fontsize=13, fontweight='bold')
axes[0].set_ylabel('Valor Real')
axes[0].set_xlabel('Predicción del Modelo')

# Curva ROC y AUC
fpr, tpr, thresholds = roc_curve(y_test, y_prob_test)
roc_auc = auc(fpr, tpr)

axes[1].plot(fpr, tpr, color='darkorange', lw=2, label=f'Curva ROC (AUC = {roc_auc:.3f})')
axes[1].plot([0, 1], [0, 1], color='navy', lw=1.5, linestyle='--', label='Azar (AUC = 0.50)')
axes[1].set_xlim([0.0, 1.0])
axes[1].set_ylim([0.0, 1.05])
axes[1].set_xlabel('Tasa de Falsos Positivos (FPR)')
axes[1].set_ylabel('Tasa de Verdaderos Positivos (TPR / Recall)')
axes[1].set_title('Curva ROC (Receiver Operating Characteristic)', fontsize=13, fontweight='bold')
axes[1].legend(loc="lower right")

# Importancia de Variables (Feature Importance)
importancias = pd.Series(modelo_rf.feature_importances_, index=features).sort_values(ascending=True)
importancias.plot(kind='barh', color='teal', ax=axes[2])
axes[2].set_title('Importancia de Variables (Feature Importance)', fontsize=13, fontweight='bold')
axes[2].set_xlabel('Ganancia / Relevancia Relativa')

plt.tight_layout()
plt.show()

#contruccion de un dataset temporal y descomposicion estacional para el analisis
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller

df_temp = df[['InvoiceDate', 'TotalAmount']].copy()
df_temp.set_index('InvoiceDate', inplace=True)

#resampling a frecuencia semanal ('W'), sumando el total vendido por semana
serie_ventas = df_temp['TotalAmount'].resample('W').sum()

#eliminar las semana final en caso de no estar completa
if len(serie_ventas) > 100:
    serie_ventas = serie_ventas[:-1]

print(f"Total de semanas: {len(serie_ventas)}")
print(f"Rango de fechas: {serie_ventas.index.min().strftime('%d/%m/%Y')} a {serie_ventas.index.max().strftime('%d/%m/%Y')}")

#Test de Estacionariedad (Dickey-Fuller Aumentado - ADF)
adf_test = adfuller(serie_ventas)
print("\n test de dickey fuller aumentado (ADF)")
print(f"Estadístico ADF: {adf_test[0]:.4f}")
print(f"p-valor: {adf_test[1]:.4f}")
if adf_test[1] <= 0.05:
    print("conclusion: La serie es Estacionaria (p <= 0.05).")
else:
    print("conclusión: La serie NO es estacionaria (p > 0.05). Requiere diferenciación.")

#descomposición de la serie: Tendencia, Estacionalidad y Residuo (visualización obligatoria)
descomposicion = seasonal_decompose(serie_ventas, model='additive', period=52) # periodo 52 semanas (1 año)

fig = descomposicion.plot()
fig.set_size_inches(14, 8)
fig.suptitle('Descomposición Temporal de Ventas Semanales (Observada, Tendencia, Estacionalidad, Residuos)', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

#modelo de series de tiempo (arima/sarima)
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error, mean_squared_error
import scipy.stats as stats

#division temporal: Train (histórico) y Test (últimas 12 semanas para pronosticar)
n_test = 12
train_ts = serie_ventas[:-n_test]
test_ts = serie_ventas[-n_test:]

print(f"Semanas de Entrenamiento (Train): {len(train_ts)}")
print(f"Semanas de Prueba (Test Horizon): {len(test_ts)}")

#Modelo ARIMA(1, 1, 1)
# Utiliza 1 autoregresivo, 1 diferenciación y 1 media móvil
modelo_arima = SARIMAX(train_ts, order=(1, 1, 1), enforce_stationarity=False, enforce_invertibility=False)
resultado_arima = modelo_arima.fit(disp=False)

#forecasting para test
predicciones_obj = resultado_arima.get_forecast(steps=n_test)
predicciones_ts = predicciones_obj.predicted_mean
intervalo_confianza = predicciones_obj.conf_int()

mae = mean_absolute_error(test_ts, predicciones_ts)
rmse = np.sqrt(mean_squared_error(test_ts, predicciones_ts))
mape = np.mean(np.abs((test_ts - predicciones_ts) / test_ts)) * 100

print("evaluacion tecnica del pronostico (test)")
print(f"MAE  (Error Absoluto Medio):           £{mae:,.2f}")
print(f"RMSE (Raíz del Error Cuadrático Medio): £{rmse:,.2f}")
print(f"MAPE (Error Porcentual Absoluto Medio): {mape:.2f}%")

# Serie Original vs Pronóstico y Diagnóstico de Residuos (visualizacion obligatoria)
fig, axes = plt.subplots(1, 2, figsize=(18, 5))

# Serie Original vs Pronóstico con Intervalos de Confianza al 95%
axes[0].plot(train_ts.index[-24:], train_ts[-24:], label='Histórico Real (Últimos 6 meses)', color='navy')
axes[0].plot(test_ts.index, test_ts, label='Real en Test', color='black', lw=2)
axes[0].plot(test_ts.index, predicciones_ts, label='Pronóstico ARIMA', color='red', linestyle='--', lw=2)
axes[0].fill_between(test_ts.index,
                     intervalo_confianza.iloc[:, 0],
                     intervalo_confianza.iloc[:, 1],
                     color='pink', alpha=0.3, label='Intervalo de Confianza 95%')
axes[0].set_title('Serie Original vs Pronóstico (Horizonte 12 Semanas)', fontsize=13, fontweight='bold')
axes[0].set_ylabel('Ventas Semanales (£)')
axes[0].legend(loc='upper left')

# Diagnóstico de Residuos (Distribución y Normalidad)
residuos = resultado_arima.resid
sns.histplot(residuos, kde=True, color='purple', ax=axes[1])
axes[1].axvline(0, color='red', linestyle='--')
axes[1].set_title('Distribución de Residuos del Modelo (Ruido Blanco)', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Error / Residuo')
axes[1].set_ylabel('Frecuencia')

plt.tight_layout()
plt.show()